# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - security
  - in progress
  - on hold
  - rfc

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  any recent activity. The incident will be closed if it remains stale. To
  prevent this issue from closing, please comment on the issue (if necessary).

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed due to lack of activity after it was marked stale.
  Let us know in Discord if this issue needs to be reopened.
